name: merge gitlab

on:
  workflow_call:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.ACTIONS_TOKEN }}

    - name: git config
      run: |
        git config --global user.name "oscam-emu"
        git config --global user.email "oscam-emu@users.noreply.github.com"

    - name: merge oscam-gitlab into master
      run: |
        if git merge --no-ff origin/oscam-gitlab -m "Auto-Merge branch 'oscam-gitlab'"; then
            git push --follow-tags origin
        else
            printf "\nfiles with merge conficts:\n"
            git diff --check
        fi
