name: sync gitlab

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: oscam-gitlab

    - name: sync
      run: |
        git config --global user.name "oscam-emu"
        git config --global user.email "oscam-emu@users.noreply.github.com"
        git remote add --track master oscam-gitlab https://git.streamboard.tv/common/oscam.git
        git pull oscam-gitlab master
        git push origin 
