name: sync gitlab

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: checkout oscam-gitlab
      uses: actions/checkout@v4
      with:
        ref: oscam-gitlab
        fetch-depth: 0
        token: ${{ secrets.ACTIONS_TOKEN }}

    - name: git config
      run: |
        git config --global user.name "oscam-emu"
        git config --global user.email "oscam-emu@users.noreply.github.com"

    - name: sync oscam-gitlab with upstream
      run: |
        git remote add --track master streamboard https://git.streamboard.tv/common/oscam.git
        git fetch streamboard
        ahead=$(git rev-list streamboard/master..HEAD --count)
        if [ $ahead -gt 0 ]; then
            force='--force'
            printf "\n$ahead commit(s) ahead upstream -> reset branch and force push changes\n"
            git reset --hard HEAD~$ahead
        fi
        git merge streamboard/master
        git push --follow-tags origin $force

  merge:
    uses: ./.github/workflows/merge-gitlab.yml
    secrets: inherit
    needs:
      - sync
